version: '3.9'

services:

  redis_dev:
    container_name: redis_dev
    image: redis:6.2.4
    ports:
      - "6379:6379"
    networks:
      - sirius_network

networks:
  sirius_network:
    external: True
